version: '3'

services:
  web:
    container_name: art_web1
    build: ./web
    command: uwsgi --ini /app/tr_art/tr_art/art_uwsgi_docker.ini
    ports:
      - "8000:8000"
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf
    depends_on:
      - db

  celery:
    container_name: art_celery1
    build: ./web
    command: celery worker -A tr_art --loglevel=debug --concurrency=4
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf

    depends_on:
      - web
      - redis

  celery-beat:
    container_name: art_celerybeat1
    build: ./web
    command: celery -A tr_art beat
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf

    depends_on:
      - web
      - redis

  db:
    container_name: art_psql1
    build: ./postgres
    expose:
      - "5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: vadim
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: tr_art
    volumes:
      - art_pgdata:/var/lib/postgresql/data

  nginx:
    container_name: art_nginx1
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../tr_art:/app/tr_art
    depends_on:
      - web

  redis:
    container_name: art_redis1
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  art_pgdata:
