version: '3'

services:
  web:
    container_name: art_web1
    build: ./web
    command: >
        sh -c "python manage.py collectstatic --no-input &&
            python manage.py makemigrations articles &&
            python manage.py migrate &&
            uwsgi --ini /app/tr_art/tr_art/art_uwsgi_docker.ini"
    ports:
      - "8000:8000"
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf
    depends_on:
      - db

  celery:
    container_name: art_celery1
    build: ./web
    command: celery worker -A tr_art --loglevel=debug --concurrency=4
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf

    depends_on:
      - web
      - redis

  celery-beat:
    container_name: art_celerybeat1
    build: ./web
    command: celery -A tr_art beat
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf

    depends_on:
      - web
      - redis

  celery-flower:
    container_name: art_celeryflower1
    build: ./web
    command: sh -c "sleep 6 && celery flower -A tr_art --port=5555"
    volumes:
      - ../tr_art:/app/tr_art
    links:
      - db:dbf
      - redis:redisf
    ports:
      - "5555:5555"
    depends_on:
      - web
      - redis

  db:
    container_name: art_psql1
    build: ./postgres
    expose:
      - "5432"
    environment:
      LC_ALL: C.UTF-8
      PG_USR: vadim
      PG_PWD: 1
      PG_DB: tr_art
    volumes:
      - art_pgdata:/var/lib/postgresql/data

  nginx:
    container_name: art_nginx1
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../tr_art:/app/tr_art
    depends_on:
      - web

  redis:
    container_name: art_redis1
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  art_pgdata:
